#:include integracao/interface/telaInicial.kv
#:include integracao/interface/dimensionamento.kv
#:include integracao/interface/correnteMagnetizacao.kv
#:include integracao/interface/fichaTecnica.kv
#:include integracao/interface/desenvolvedores.kv

#:include integracao/interface/templates.kv
#:import MatplotFigure integracao.modulos.graph_widget

MDScreenManager:

    TelaInicial:
    Dimensionamento:
    CorrenteMagnetizacao:
    FichaTecnica:
    Desenvolvedores: