#:include ../integracao/interface/telaInicial.kv
#:include ../integracao/interface/dimensionamento.kv
#:include ../integracao/interface/CorrenteMagnetizacao.kv
#:include ../integracao/interface/fichaTecnica.kv
#:include ../integracao/interface/desenvolvedores.kv

#:include ../integracao/interface/templates.kv


MDScreenManager:

    TelaInicial:
    Dimensionamento:
    CorrenteMagnetizacao:
    FichaTecnica:
    Desenvolvedores: